name: chat-app

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-app
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - chat-app
    ports:
      - 5000:5000
    depends_on:
      - mongo
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - chat-app
    ports:
      - 5173:5173
    depends_on:
      - api
  caddy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - chat-app
    depends_on:
      - api
      - frontend
    
volumes:
  mongo_data:
  caddy_data:
  caddy_config:
networks:
  chat-app:
    driver: bridge
